gdax:
  api:
    baseUrl: "https://api.gdax.com/"
  key: "dd6db505beedd91501f843e192e507ef"
  secret: "zIOSBb9UWrpaRnqVCNlkkAiTqaAp92korDZmJGHdubAu5pQiOUDG1lyuhiWiRq7mSdfWp/jRFU329F31PjDfVg=="
  passphrase: "113x6awmc6zr"

websocket:
  baseUrl: "wss://ws-feed.gdax.com/"

gui:
  enabled: false